// Generated by gencpp from file rosarnl/LoadMapFile.msg
// DO NOT EDIT!


#ifndef ROSARNL_MESSAGE_LOADMAPFILE_H
#define ROSARNL_MESSAGE_LOADMAPFILE_H

#include <ros/service_traits.h>


#include <rosarnl/LoadMapFileRequest.h>
#include <rosarnl/LoadMapFileResponse.h>


namespace rosarnl
{

struct LoadMapFile
{

typedef LoadMapFileRequest Request;
typedef LoadMapFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMapFile
} // namespace rosarnl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosarnl::LoadMapFile > {
  static const char* value()
  {
    return "4de3d9cc11cc57aecc1e3b15cb59ccfc";
  }

  static const char* value(const ::rosarnl::LoadMapFile&) { return value(); }
};

template<>
struct DataType< ::rosarnl::LoadMapFile > {
  static const char* value()
  {
    return "rosarnl/LoadMapFile";
  }

  static const char* value(const ::rosarnl::LoadMapFile&) { return value(); }
};


// service_traits::MD5Sum< ::rosarnl::LoadMapFileRequest> should match 
// service_traits::MD5Sum< ::rosarnl::LoadMapFile > 
template<>
struct MD5Sum< ::rosarnl::LoadMapFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosarnl::LoadMapFile >::value();
  }
  static const char* value(const ::rosarnl::LoadMapFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosarnl::LoadMapFileRequest> should match 
// service_traits::DataType< ::rosarnl::LoadMapFile > 
template<>
struct DataType< ::rosarnl::LoadMapFileRequest>
{
  static const char* value()
  {
    return DataType< ::rosarnl::LoadMapFile >::value();
  }
  static const char* value(const ::rosarnl::LoadMapFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosarnl::LoadMapFileResponse> should match 
// service_traits::MD5Sum< ::rosarnl::LoadMapFile > 
template<>
struct MD5Sum< ::rosarnl::LoadMapFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosarnl::LoadMapFile >::value();
  }
  static const char* value(const ::rosarnl::LoadMapFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosarnl::LoadMapFileResponse> should match 
// service_traits::DataType< ::rosarnl::LoadMapFile > 
template<>
struct DataType< ::rosarnl::LoadMapFileResponse>
{
  static const char* value()
  {
    return DataType< ::rosarnl::LoadMapFile >::value();
  }
  static const char* value(const ::rosarnl::LoadMapFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSARNL_MESSAGE_LOADMAPFILE_H
