// Generated by gencpp from file rosarnl/LoadMapFileRequest.msg
// DO NOT EDIT!


#ifndef ROSARNL_MESSAGE_LOADMAPFILEREQUEST_H
#define ROSARNL_MESSAGE_LOADMAPFILEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosarnl
{
template <class ContainerAllocator>
struct LoadMapFileRequest_
{
  typedef LoadMapFileRequest_<ContainerAllocator> Type;

  LoadMapFileRequest_()
    : filename()  {
    }
  LoadMapFileRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadMapFileRequest_

typedef ::rosarnl::LoadMapFileRequest_<std::allocator<void> > LoadMapFileRequest;

typedef boost::shared_ptr< ::rosarnl::LoadMapFileRequest > LoadMapFileRequestPtr;
typedef boost::shared_ptr< ::rosarnl::LoadMapFileRequest const> LoadMapFileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosarnl::LoadMapFileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosarnl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'rosarnl': ['/home/seekurjr/catkin_ws/src/ros-arnl/msg', '/home/seekurjr/catkin_ws/devel/share/rosarnl/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::rosarnl::LoadMapFileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosarnl/LoadMapFileRequest";
  }

  static const char* value(const ::rosarnl::LoadMapFileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filename\n\
";
  }

  static const char* value(const ::rosarnl::LoadMapFileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadMapFileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosarnl::LoadMapFileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosarnl::LoadMapFileRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSARNL_MESSAGE_LOADMAPFILEREQUEST_H
