// Generated by gencpp from file rosarnl/MakePlan.msg
// DO NOT EDIT!


#ifndef ROSARNL_MESSAGE_MAKEPLAN_H
#define ROSARNL_MESSAGE_MAKEPLAN_H

#include <ros/service_traits.h>


#include <rosarnl/MakePlanRequest.h>
#include <rosarnl/MakePlanResponse.h>


namespace rosarnl
{

struct MakePlan
{

typedef MakePlanRequest Request;
typedef MakePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakePlan
} // namespace rosarnl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosarnl::MakePlan > {
  static const char* value()
  {
    return "b65e2aca742d0e735deda3ef99144bd5";
  }

  static const char* value(const ::rosarnl::MakePlan&) { return value(); }
};

template<>
struct DataType< ::rosarnl::MakePlan > {
  static const char* value()
  {
    return "rosarnl/MakePlan";
  }

  static const char* value(const ::rosarnl::MakePlan&) { return value(); }
};


// service_traits::MD5Sum< ::rosarnl::MakePlanRequest> should match 
// service_traits::MD5Sum< ::rosarnl::MakePlan > 
template<>
struct MD5Sum< ::rosarnl::MakePlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosarnl::MakePlan >::value();
  }
  static const char* value(const ::rosarnl::MakePlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosarnl::MakePlanRequest> should match 
// service_traits::DataType< ::rosarnl::MakePlan > 
template<>
struct DataType< ::rosarnl::MakePlanRequest>
{
  static const char* value()
  {
    return DataType< ::rosarnl::MakePlan >::value();
  }
  static const char* value(const ::rosarnl::MakePlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosarnl::MakePlanResponse> should match 
// service_traits::MD5Sum< ::rosarnl::MakePlan > 
template<>
struct MD5Sum< ::rosarnl::MakePlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosarnl::MakePlan >::value();
  }
  static const char* value(const ::rosarnl::MakePlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosarnl::MakePlanResponse> should match 
// service_traits::DataType< ::rosarnl::MakePlan > 
template<>
struct DataType< ::rosarnl::MakePlanResponse>
{
  static const char* value()
  {
    return DataType< ::rosarnl::MakePlan >::value();
  }
  static const char* value(const ::rosarnl::MakePlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSARNL_MESSAGE_MAKEPLAN_H
