// Generated by gencpp from file schunk_sdh/PressureArrayList.msg
// DO NOT EDIT!


#ifndef SCHUNK_SDH_MESSAGE_PRESSUREARRAYLIST_H
#define SCHUNK_SDH_MESSAGE_PRESSUREARRAYLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <schunk_sdh/PressureArray.h>

namespace schunk_sdh
{
template <class ContainerAllocator>
struct PressureArrayList_
{
  typedef PressureArrayList_<ContainerAllocator> Type;

  PressureArrayList_()
    : header()
    , pressure_list()  {
    }
  PressureArrayList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pressure_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::schunk_sdh::PressureArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::schunk_sdh::PressureArray_<ContainerAllocator> >::other >  _pressure_list_type;
  _pressure_list_type pressure_list;





  typedef boost::shared_ptr< ::schunk_sdh::PressureArrayList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_sdh::PressureArrayList_<ContainerAllocator> const> ConstPtr;

}; // struct PressureArrayList_

typedef ::schunk_sdh::PressureArrayList_<std::allocator<void> > PressureArrayList;

typedef boost::shared_ptr< ::schunk_sdh::PressureArrayList > PressureArrayListPtr;
typedef boost::shared_ptr< ::schunk_sdh::PressureArrayList const> PressureArrayListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::schunk_sdh::PressureArrayList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace schunk_sdh

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'schunk_sdh': ['/home/seekurjr/catkin_ws/src/schunk_modular_robotics/schunk_sdh/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::schunk_sdh::PressureArrayList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::schunk_sdh::PressureArrayList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::schunk_sdh::PressureArrayList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bc84d413df668b4cdc5d431fe62d2de";
  }

  static const char* value(const ::schunk_sdh::PressureArrayList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bc84d413df668b4ULL;
  static const uint64_t static_value2 = 0xcdc5d431fe62d2deULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "schunk_sdh/PressureArrayList";
  }

  static const char* value(const ::schunk_sdh::PressureArrayList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
schunk_sdh/PressureArray[] pressure_list\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: schunk_sdh/PressureArray\n\
string sensor_name\n\
uint16 cells_x\n\
uint16 cells_y\n\
float64[] pressure  # unit: Pascal (Pa)\n\
";
  }

  static const char* value(const ::schunk_sdh::PressureArrayList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pressure_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PressureArrayList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_sdh::PressureArrayList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::schunk_sdh::PressureArrayList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pressure_list[]" << std::endl;
    for (size_t i = 0; i < v.pressure_list.size(); ++i)
    {
      s << indent << "  pressure_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::schunk_sdh::PressureArray_<ContainerAllocator> >::stream(s, indent + "    ", v.pressure_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHUNK_SDH_MESSAGE_PRESSUREARRAYLIST_H
